### ISSUE TITLE
HLS_Use_Model/AXI_Sample missing #include statement

### ISSUE THREAD

**Issue by dsp-avt** [Xilinx/xfopencv#27]
OS: Windows 10
Tool Version: 2018.3

The HLS_Use_Model/AXI_Sample is missing a #include "common/xf_axi.h" statement that causes C Simulation to fail.  Adding that #include statement to the bottom of the xf_header.h file fixes the issue.  

Here's the error before adding the #include statement:
![image](https://user-images.githubusercontent.com/41306270/51045035-3591e480-1588-11e9-97a1-e8046e5cfa86.png)

Also, I had to increase the stack space in order to run the simulation.  I saw the following error which I tracked down to running out of memory:
![image](https://user-images.githubusercontent.com/41306270/51045070-4f332c00-1588-11e9-8f83-35a291fd5a4f.png)

I increased the stack space to 1GB by using the menu bar to navigating to Project > Project Settings > Simulation.
![image](https://user-images.githubusercontent.com/41306270/51045171-902b4080-1588-11e9-8625-b12b9e8ab638.png)

**Comment by bgouthamb** [comment]
Hello @dsp-avt ,

Thanks for pointing out the missing #include. Corrected it.

Regarding the stack space issue, the __XFCV_HLS_MODEL__ flag makes the xf::Mat object to form array(s ) of fixed size, instead of pointer(s), to facilitate standalone HLS Synthesis and Co-Sim. These array(s) consume the stack memory heavily. Hence, increasing the stack size is necessary when working with larger image sizes (especially in Windows which has a very less default stack size of 1MB). This constraint will be addressed in the upcoming release.

**Comment by bgouthamb** [comment]
Issue has been resolved in the latest release. Reopen if needed.
